In [1]:
'''
challenge: resnet input: 3 channels images, the mri images: 20 channels
-> 1 layer (conv2d) to transform 16 to 3 berfore resnet model

challenge: using pretrained resent50 model and update all parameters (aksh-ai)
or just fine tune last layer
-> update all parameters
challenge: resnet-50 transform normalizing is not applicable
we have gray scale 18 channel data 
'''


'\nchallenge: resnet input: 3 channels images, the mri images: 20 channels\n-> 1 layer (conv2d) to transform 16 to 3 berfore resnet model\n\nchallenge: using pretrained resent50 model and update all parameters (aksh-ai)\nor just fine tune last layer\n-> update all parameters\nchallenge: resnet-50 transform normalizing is not applicable\nwe have gray scale 18 channel data \n'

In [2]:
import os

import numpy as np
import pandas as pd
from sklearn.utils.class_weight import compute_class_weight

import torch
import torch.nn as nn
import torch.optim as optim
from torchvision import transforms
from torch.utils.data import DataLoader

from config import Config, Device
from datasets import MRIDataset
from models import MriResentModel
from train import Trainer
from test_file import Tester

In [3]:
device = Device.device
print(device)

mps


In [4]:
data_path = os.path.join(os.getcwd(), "data")
labels_path = "train.csv"

batch_size = Config.batch_size
num_epochs = Config.num_epochs
learning_rate = Config.learning_rate
image_size = 256

In [5]:
train_transforms = transforms.Compose([
    transforms.ToTensor(),
    transforms.Resize((image_size, image_size)),
    transforms.RandomHorizontalFlip(),
    transforms.RandomRotation(10),
    # transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
])

test_transforms = transforms.Compose([
    transforms.ToTensor(),
    transforms.Resize((image_size, image_size)),
    # transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
])

In [6]:
train_dataset = MRIDataset(
    data_path, labels_path, split="train", transform=train_transforms, max_slices=20)
    
val_dataset = MRIDataset(data_path, labels_path, split="val",
                         transform=test_transforms, max_slices=20)
test_dataset = MRIDataset(
    data_path, labels_path, split="test", transform=test_transforms, max_slices=20)


train_dl = DataLoader(train_dataset, batch_size, shuffle=True)
val_dl = DataLoader(val_dataset, batch_size)
test_dl = DataLoader(test_dataset, batch_size)

In [7]:
model = MriResentModel(20,1).to(device)
model

/Users/fateme/Projects/iaaa-project/iaaa-venv/lib/python3.12/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/Users/fateme/Projects/iaaa-project/iaaa-venv/lib/python3.12/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=ResNet50_Weights.IMAGENET1K_V1`. You can also use `weights=ResNet50_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)


MriResentModel(
  (conv): Conv2d(20, 3, kernel_size=(1, 1), stride=(1, 1))
  (resnet_model): ResNet(
    (conv1): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
    (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (relu): ReLU(inplace=True)
    (maxpool): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
    (layer1): Sequential(
      (0): Bottleneck(
        (conv1): Conv2d(64, 64, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (conv3): Conv2d(64, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (bn3): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        

In [8]:
def compute_class_weights_from_csv(csv_file_path):
    # Read the CSV file
    df = pd.read_csv(csv_file_path)

    labels = df['prediction'].values

    # Convert labels to integers if they are not already
    labels = labels.astype(int)

    # Compute class weights
    unique_labels = np.unique(labels)
    class_weights = compute_class_weight(
        class_weight='balanced', classes=unique_labels, y=labels)

    # Convert to torch tensor
    return torch.tensor(class_weights, dtype=torch.float)


# Path to your CSV file
class_weights = compute_class_weights_from_csv(labels_path)
print(class_weights)
# For binary classification, use the appropriate class weight
# Assuming binary classification with class labels 0 and 1
class_weights = class_weights[1]  # Adjust if necessary
print("Class Weights:", class_weights)

tensor([0.5713, 4.0051])
Class Weights: tensor(4.0051)


In [9]:
# loss and optimizer

# criterion = nn.BCEWithLogitsLoss().to(device)
criterion = nn.BCEWithLogitsLoss(pos_weight=class_weights).to(device)
# criterion = nn.CrossEntropyLoss().to(device)
optimizer = optim.SGD(model.parameters(), lr=0.01, momentum=0.9, weight_decay=1e-4)

In [10]:
model_name = model.__class__.__name__
model_name

'MriResentModel'

In [11]:
trainer = Trainer(
    model=model,
    criterion=criterion,
    optimizer=optimizer,
    train_dl=train_dl,
    val_dl=val_dl,
    train_dataset=train_dataset,
    val_dataset=val_dataset,
    device=device,
    num_epochs=100,
    patience=50,
    threshold=0,
    save_path=f"saved_models/{model_name}.pth"
)

# Start training
trainer.train()

100%|██████████| 59/59 [03:03<00:00,  3.10s/it]


Confusion Matrix:
[[  0 548]
 [  0  78]]
Epoch 1/100, Train Loss: 108.5508, Train Accuracy: 0.1250
Epoch 1/100, Val Accuracy: 0.1246, Precision: 0.1246, Recall: 1.0000, AUC: 0.5000, Avg Metric: 0.5415


100%|██████████| 59/59 [02:58<00:00,  3.03s/it]


Confusion Matrix:
[[  0 548]
 [  0  78]]
Epoch 2/100, Train Loss: 125.3991, Train Accuracy: 0.1255
Epoch 2/100, Val Accuracy: 0.1246, Precision: 0.1246, Recall: 1.0000, AUC: 0.5139, Avg Metric: 0.5462


100%|██████████| 59/59 [03:00<00:00,  3.05s/it]


Confusion Matrix:
[[  0 548]
 [  0  78]]
Epoch 3/100, Train Loss: 75.0770, Train Accuracy: 0.1250
Epoch 3/100, Val Accuracy: 0.1246, Precision: 0.1246, Recall: 1.0000, AUC: 0.5125, Avg Metric: 0.5457


100%|██████████| 59/59 [03:01<00:00,  3.07s/it]


Confusion Matrix:
[[ 13 535]
 [  2  76]]
Epoch 4/100, Train Loss: 57.2313, Train Accuracy: 0.1250
Epoch 4/100, Val Accuracy: 0.1422, Precision: 0.1244, Recall: 0.9744, AUC: 0.4745, Avg Metric: 0.5244


100%|██████████| 59/59 [03:04<00:00,  3.12s/it]


Confusion Matrix:
[[  0 548]
 [  0  78]]
Epoch 5/100, Train Loss: 56.1505, Train Accuracy: 0.1250
Epoch 5/100, Val Accuracy: 0.1246, Precision: 0.1246, Recall: 1.0000, AUC: 0.5206, Avg Metric: 0.5484


100%|██████████| 59/59 [03:02<00:00,  3.09s/it]


Confusion Matrix:
[[  0 548]
 [  0  78]]
Epoch 6/100, Train Loss: 55.3161, Train Accuracy: 0.1250
Epoch 6/100, Val Accuracy: 0.1246, Precision: 0.1246, Recall: 1.0000, AUC: 0.5221, Avg Metric: 0.5489


100%|██████████| 59/59 [03:11<00:00,  3.24s/it]


Confusion Matrix:
[[  0 548]
 [  0  78]]
Epoch 7/100, Train Loss: 53.2724, Train Accuracy: 0.1250
Epoch 7/100, Val Accuracy: 0.1246, Precision: 0.1246, Recall: 1.0000, AUC: 0.5227, Avg Metric: 0.5491


100%|██████████| 59/59 [03:17<00:00,  3.34s/it]


Confusion Matrix:
[[  0 548]
 [  0  78]]
Epoch 8/100, Train Loss: 53.8397, Train Accuracy: 0.1250
Epoch 8/100, Val Accuracy: 0.1246, Precision: 0.1246, Recall: 1.0000, AUC: 0.5088, Avg Metric: 0.5445


100%|██████████| 59/59 [03:02<00:00,  3.09s/it]


Confusion Matrix:
[[  0 548]
 [  0  78]]
Epoch 9/100, Train Loss: 52.8057, Train Accuracy: 0.1250
Epoch 9/100, Val Accuracy: 0.1246, Precision: 0.1246, Recall: 1.0000, AUC: 0.5139, Avg Metric: 0.5462


100%|██████████| 59/59 [03:04<00:00,  3.12s/it]


Confusion Matrix:
[[  0 548]
 [  0  78]]
Epoch 10/100, Train Loss: 53.3605, Train Accuracy: 0.1250
Epoch 10/100, Val Accuracy: 0.1246, Precision: 0.1246, Recall: 1.0000, AUC: 0.5312, Avg Metric: 0.5519


100%|██████████| 59/59 [03:03<00:00,  3.12s/it]


Confusion Matrix:
[[  0 548]
 [  0  78]]
Epoch 11/100, Train Loss: 52.9281, Train Accuracy: 0.1250
Epoch 11/100, Val Accuracy: 0.1246, Precision: 0.1246, Recall: 1.0000, AUC: 0.5386, Avg Metric: 0.5544


100%|██████████| 59/59 [03:03<00:00,  3.10s/it]


Confusion Matrix:
[[  0 548]
 [  0  78]]
Epoch 12/100, Train Loss: 52.9736, Train Accuracy: 0.1250
Epoch 12/100, Val Accuracy: 0.1246, Precision: 0.1246, Recall: 1.0000, AUC: 0.5203, Avg Metric: 0.5483


100%|██████████| 59/59 [03:03<00:00,  3.12s/it]


Confusion Matrix:
[[  0 548]
 [  0  78]]
Epoch 13/100, Train Loss: 53.1612, Train Accuracy: 0.1250
Epoch 13/100, Val Accuracy: 0.1246, Precision: 0.1246, Recall: 1.0000, AUC: 0.5329, Avg Metric: 0.5525


100%|██████████| 59/59 [03:03<00:00,  3.11s/it]


Confusion Matrix:
[[  0 548]
 [  0  78]]
Epoch 14/100, Train Loss: 52.8059, Train Accuracy: 0.1250
Epoch 14/100, Val Accuracy: 0.1246, Precision: 0.1246, Recall: 1.0000, AUC: 0.5269, Avg Metric: 0.5505


100%|██████████| 59/59 [03:02<00:00,  3.10s/it]


Confusion Matrix:
[[  0 548]
 [  0  78]]
Epoch 15/100, Train Loss: 53.1732, Train Accuracy: 0.1250
Epoch 15/100, Val Accuracy: 0.1246, Precision: 0.1246, Recall: 1.0000, AUC: 0.5334, Avg Metric: 0.5527


100%|██████████| 59/59 [03:03<00:00,  3.10s/it]


Confusion Matrix:
[[  0 548]
 [  0  78]]
Epoch 16/100, Train Loss: 52.8623, Train Accuracy: 0.1250
Epoch 16/100, Val Accuracy: 0.1246, Precision: 0.1246, Recall: 1.0000, AUC: 0.5269, Avg Metric: 0.5505


100%|██████████| 59/59 [03:02<00:00,  3.10s/it]


Confusion Matrix:
[[  0 548]
 [  0  78]]
Epoch 17/100, Train Loss: 53.3531, Train Accuracy: 0.1250
Epoch 17/100, Val Accuracy: 0.1246, Precision: 0.1246, Recall: 1.0000, AUC: 0.5288, Avg Metric: 0.5511


100%|██████████| 59/59 [03:00<00:00,  3.07s/it]


Confusion Matrix:
[[  0 548]
 [  0  78]]
Epoch 18/100, Train Loss: 52.8942, Train Accuracy: 0.1250
Epoch 18/100, Val Accuracy: 0.1246, Precision: 0.1246, Recall: 1.0000, AUC: 0.5104, Avg Metric: 0.5450


100%|██████████| 59/59 [03:02<00:00,  3.09s/it]


Confusion Matrix:
[[  0 548]
 [  0  78]]
Epoch 19/100, Train Loss: 52.6823, Train Accuracy: 0.1250
Epoch 19/100, Val Accuracy: 0.1246, Precision: 0.1246, Recall: 1.0000, AUC: 0.5461, Avg Metric: 0.5569


100%|██████████| 59/59 [03:01<00:00,  3.07s/it]


Confusion Matrix:
[[  0 548]
 [  0  78]]
Epoch 20/100, Train Loss: 53.0765, Train Accuracy: 0.1250
Epoch 20/100, Val Accuracy: 0.1246, Precision: 0.1246, Recall: 1.0000, AUC: 0.5528, Avg Metric: 0.5591


100%|██████████| 59/59 [03:01<00:00,  3.07s/it]


Confusion Matrix:
[[  0 548]
 [  0  78]]
Epoch 21/100, Train Loss: 52.8048, Train Accuracy: 0.1250
Epoch 21/100, Val Accuracy: 0.1246, Precision: 0.1246, Recall: 1.0000, AUC: 0.5481, Avg Metric: 0.5576


100%|██████████| 59/59 [03:02<00:00,  3.10s/it]


Confusion Matrix:
[[  0 548]
 [  0  78]]
Epoch 22/100, Train Loss: 52.5280, Train Accuracy: 0.1250
Epoch 22/100, Val Accuracy: 0.1246, Precision: 0.1246, Recall: 1.0000, AUC: 0.5353, Avg Metric: 0.5533


100%|██████████| 59/59 [03:01<00:00,  3.07s/it]


Confusion Matrix:
[[  0 548]
 [  0  78]]
Epoch 23/100, Train Loss: 52.3735, Train Accuracy: 0.1250
Epoch 23/100, Val Accuracy: 0.1246, Precision: 0.1246, Recall: 1.0000, AUC: 0.5334, Avg Metric: 0.5527


100%|██████████| 59/59 [03:00<00:00,  3.06s/it]


Confusion Matrix:
[[  0 548]
 [  0  78]]
Epoch 24/100, Train Loss: 52.7954, Train Accuracy: 0.1250
Epoch 24/100, Val Accuracy: 0.1246, Precision: 0.1246, Recall: 1.0000, AUC: 0.5179, Avg Metric: 0.5475


100%|██████████| 59/59 [03:00<00:00,  3.06s/it]


Confusion Matrix:
[[  0 548]
 [  0  78]]
Epoch 25/100, Train Loss: 52.6818, Train Accuracy: 0.1250
Epoch 25/100, Val Accuracy: 0.1246, Precision: 0.1246, Recall: 1.0000, AUC: 0.5284, Avg Metric: 0.5510


100%|██████████| 59/59 [03:00<00:00,  3.07s/it]


Confusion Matrix:
[[  0 548]
 [  0  78]]
Epoch 26/100, Train Loss: 52.7201, Train Accuracy: 0.1250
Epoch 26/100, Val Accuracy: 0.1246, Precision: 0.1246, Recall: 1.0000, AUC: 0.5357, Avg Metric: 0.5534


100%|██████████| 59/59 [03:01<00:00,  3.07s/it]


Confusion Matrix:
[[  0 548]
 [  0  78]]
Epoch 27/100, Train Loss: 52.7641, Train Accuracy: 0.1250
Epoch 27/100, Val Accuracy: 0.1246, Precision: 0.1246, Recall: 1.0000, AUC: 0.5201, Avg Metric: 0.5482


100%|██████████| 59/59 [02:54<00:00,  2.96s/it]


Confusion Matrix:
[[  0 548]
 [  0  78]]
Epoch 28/100, Train Loss: 53.0213, Train Accuracy: 0.1250
Epoch 28/100, Val Accuracy: 0.1246, Precision: 0.1246, Recall: 1.0000, AUC: 0.5150, Avg Metric: 0.5465


100%|██████████| 59/59 [02:50<00:00,  2.89s/it]


Confusion Matrix:
[[  0 548]
 [  0  78]]
Epoch 29/100, Train Loss: 52.7518, Train Accuracy: 0.1250
Epoch 29/100, Val Accuracy: 0.1246, Precision: 0.1246, Recall: 1.0000, AUC: 0.5142, Avg Metric: 0.5463


100%|██████████| 59/59 [02:52<00:00,  2.93s/it]


Confusion Matrix:
[[  0 548]
 [  0  78]]
Epoch 30/100, Train Loss: 52.4431, Train Accuracy: 0.1250
Epoch 30/100, Val Accuracy: 0.1246, Precision: 0.1246, Recall: 1.0000, AUC: 0.5136, Avg Metric: 0.5461


100%|██████████| 59/59 [03:00<00:00,  3.05s/it]


Confusion Matrix:
[[  0 548]
 [  0  78]]
Epoch 31/100, Train Loss: 52.6693, Train Accuracy: 0.1250
Epoch 31/100, Val Accuracy: 0.1246, Precision: 0.1246, Recall: 1.0000, AUC: 0.5330, Avg Metric: 0.5525


100%|██████████| 59/59 [02:59<00:00,  3.04s/it]


Confusion Matrix:
[[  0 548]
 [  0  78]]
Epoch 32/100, Train Loss: 52.8984, Train Accuracy: 0.1250
Epoch 32/100, Val Accuracy: 0.1246, Precision: 0.1246, Recall: 1.0000, AUC: 0.5229, Avg Metric: 0.5492


100%|██████████| 59/59 [03:01<00:00,  3.08s/it]


Confusion Matrix:
[[  0 548]
 [  0  78]]
Epoch 33/100, Train Loss: 52.4524, Train Accuracy: 0.1250
Epoch 33/100, Val Accuracy: 0.1246, Precision: 0.1246, Recall: 1.0000, AUC: 0.5185, Avg Metric: 0.5477


100%|██████████| 59/59 [03:01<00:00,  3.08s/it]


Confusion Matrix:
[[  0 548]
 [  0  78]]
Epoch 34/100, Train Loss: 52.6840, Train Accuracy: 0.1250
Epoch 34/100, Val Accuracy: 0.1246, Precision: 0.1246, Recall: 1.0000, AUC: 0.5297, Avg Metric: 0.5514


100%|██████████| 59/59 [03:01<00:00,  3.08s/it]


Confusion Matrix:
[[  0 548]
 [  0  78]]
Epoch 35/100, Train Loss: 52.5402, Train Accuracy: 0.1250
Epoch 35/100, Val Accuracy: 0.1246, Precision: 0.1246, Recall: 1.0000, AUC: 0.5230, Avg Metric: 0.5492


100%|██████████| 59/59 [02:59<00:00,  3.05s/it]


Confusion Matrix:
[[  0 548]
 [  0  78]]
Epoch 36/100, Train Loss: 52.8478, Train Accuracy: 0.1250
Epoch 36/100, Val Accuracy: 0.1246, Precision: 0.1246, Recall: 1.0000, AUC: 0.5333, Avg Metric: 0.5526


100%|██████████| 59/59 [02:59<00:00,  3.05s/it]


Confusion Matrix:
[[  0 548]
 [  0  78]]
Epoch 37/100, Train Loss: 52.7289, Train Accuracy: 0.1250
Epoch 37/100, Val Accuracy: 0.1246, Precision: 0.1246, Recall: 1.0000, AUC: 0.5166, Avg Metric: 0.5471


100%|██████████| 59/59 [02:59<00:00,  3.05s/it]


Confusion Matrix:
[[  0 548]
 [  0  78]]
Epoch 38/100, Train Loss: 52.4584, Train Accuracy: 0.1250
Epoch 38/100, Val Accuracy: 0.1246, Precision: 0.1246, Recall: 1.0000, AUC: 0.5197, Avg Metric: 0.5481


100%|██████████| 59/59 [02:59<00:00,  3.04s/it]


Confusion Matrix:
[[  0 548]
 [  0  78]]
Epoch 39/100, Train Loss: 52.6853, Train Accuracy: 0.1250
Epoch 39/100, Val Accuracy: 0.1246, Precision: 0.1246, Recall: 1.0000, AUC: 0.5054, Avg Metric: 0.5433


100%|██████████| 59/59 [03:00<00:00,  3.05s/it]


Confusion Matrix:
[[  0 548]
 [  0  78]]
Epoch 40/100, Train Loss: 52.1425, Train Accuracy: 0.1250
Epoch 40/100, Val Accuracy: 0.1246, Precision: 0.1246, Recall: 1.0000, AUC: 0.5116, Avg Metric: 0.5454


100%|██████████| 59/59 [02:59<00:00,  3.05s/it]


Confusion Matrix:
[[  0 548]
 [  0  78]]
Epoch 41/100, Train Loss: 52.4929, Train Accuracy: 0.1250
Epoch 41/100, Val Accuracy: 0.1246, Precision: 0.1246, Recall: 1.0000, AUC: 0.5153, Avg Metric: 0.5466


100%|██████████| 59/59 [02:59<00:00,  3.04s/it]


Confusion Matrix:
[[  0 548]
 [  0  78]]
Epoch 42/100, Train Loss: 52.4282, Train Accuracy: 0.1250
Epoch 42/100, Val Accuracy: 0.1246, Precision: 0.1246, Recall: 1.0000, AUC: 0.5226, Avg Metric: 0.5491


100%|██████████| 59/59 [02:59<00:00,  3.04s/it]


Confusion Matrix:
[[  0 548]
 [  0  78]]
Epoch 43/100, Train Loss: 52.1727, Train Accuracy: 0.1250
Epoch 43/100, Val Accuracy: 0.1246, Precision: 0.1246, Recall: 1.0000, AUC: 0.5268, Avg Metric: 0.5505


100%|██████████| 59/59 [02:59<00:00,  3.05s/it]


Confusion Matrix:
[[  0 548]
 [  0  78]]
Epoch 44/100, Train Loss: 53.2181, Train Accuracy: 0.1250
Epoch 44/100, Val Accuracy: 0.1246, Precision: 0.1246, Recall: 1.0000, AUC: 0.5162, Avg Metric: 0.5469


100%|██████████| 59/59 [02:59<00:00,  3.05s/it]


Confusion Matrix:
[[  0 548]
 [  0  78]]
Epoch 45/100, Train Loss: 52.3785, Train Accuracy: 0.1250
Epoch 45/100, Val Accuracy: 0.1246, Precision: 0.1246, Recall: 1.0000, AUC: 0.5025, Avg Metric: 0.5424


100%|██████████| 59/59 [03:00<00:00,  3.05s/it]


Confusion Matrix:
[[  0 548]
 [  0  78]]
Epoch 46/100, Train Loss: 52.1674, Train Accuracy: 0.1250
Epoch 46/100, Val Accuracy: 0.1246, Precision: 0.1246, Recall: 1.0000, AUC: 0.5112, Avg Metric: 0.5453


100%|██████████| 59/59 [03:00<00:00,  3.06s/it]


Confusion Matrix:
[[  0 548]
 [  0  78]]
Epoch 47/100, Train Loss: 52.2234, Train Accuracy: 0.1250
Epoch 47/100, Val Accuracy: 0.1246, Precision: 0.1246, Recall: 1.0000, AUC: 0.5099, Avg Metric: 0.5448


100%|██████████| 59/59 [03:00<00:00,  3.06s/it]


Confusion Matrix:
[[  0 548]
 [  0  78]]
Epoch 48/100, Train Loss: 52.5572, Train Accuracy: 0.1250
Epoch 48/100, Val Accuracy: 0.1246, Precision: 0.1246, Recall: 1.0000, AUC: 0.5223, Avg Metric: 0.5490


100%|██████████| 59/59 [02:53<00:00,  2.94s/it]


Confusion Matrix:
[[  0 548]
 [  0  78]]
Epoch 49/100, Train Loss: 51.9153, Train Accuracy: 0.1250
Epoch 49/100, Val Accuracy: 0.1246, Precision: 0.1246, Recall: 1.0000, AUC: 0.5144, Avg Metric: 0.5463


100%|██████████| 59/59 [02:47<00:00,  2.85s/it]


Confusion Matrix:
[[  0 548]
 [  0  78]]
Epoch 50/100, Train Loss: 52.7574, Train Accuracy: 0.1250
Epoch 50/100, Val Accuracy: 0.1246, Precision: 0.1246, Recall: 1.0000, AUC: 0.5285, Avg Metric: 0.5510


100%|██████████| 59/59 [02:48<00:00,  2.85s/it]


Confusion Matrix:
[[  0 548]
 [  0  78]]
Epoch 51/100, Train Loss: 51.7009, Train Accuracy: 0.1250
Epoch 51/100, Val Accuracy: 0.1246, Precision: 0.1246, Recall: 1.0000, AUC: 0.5213, Avg Metric: 0.5486


100%|██████████| 59/59 [02:48<00:00,  2.85s/it]


Confusion Matrix:
[[  0 548]
 [  0  78]]
Epoch 52/100, Train Loss: 52.1258, Train Accuracy: 0.1250
Epoch 52/100, Val Accuracy: 0.1246, Precision: 0.1246, Recall: 1.0000, AUC: 0.5329, Avg Metric: 0.5525


100%|██████████| 59/59 [02:48<00:00,  2.85s/it]


Confusion Matrix:
[[  0 548]
 [  0  78]]
Epoch 53/100, Train Loss: 51.8648, Train Accuracy: 0.1250
Epoch 53/100, Val Accuracy: 0.1246, Precision: 0.1246, Recall: 1.0000, AUC: 0.5256, Avg Metric: 0.5501


100%|██████████| 59/59 [02:48<00:00,  2.86s/it]


Confusion Matrix:
[[  0 548]
 [  0  78]]
Epoch 54/100, Train Loss: 51.5537, Train Accuracy: 0.1250
Epoch 54/100, Val Accuracy: 0.1246, Precision: 0.1246, Recall: 1.0000, AUC: 0.5447, Avg Metric: 0.5564


100%|██████████| 59/59 [02:48<00:00,  2.86s/it]


Confusion Matrix:
[[  0 548]
 [  0  78]]
Epoch 55/100, Train Loss: 52.0584, Train Accuracy: 0.1250
Epoch 55/100, Val Accuracy: 0.1246, Precision: 0.1246, Recall: 1.0000, AUC: 0.5289, Avg Metric: 0.5512


100%|██████████| 59/59 [02:48<00:00,  2.86s/it]


Confusion Matrix:
[[  0 548]
 [  0  78]]
Epoch 56/100, Train Loss: 51.7471, Train Accuracy: 0.1250
Epoch 56/100, Val Accuracy: 0.1246, Precision: 0.1246, Recall: 1.0000, AUC: 0.5200, Avg Metric: 0.5482


100%|██████████| 59/59 [02:48<00:00,  2.85s/it]


Confusion Matrix:
[[  0 548]
 [  0  78]]
Epoch 57/100, Train Loss: 51.1895, Train Accuracy: 0.1250
Epoch 57/100, Val Accuracy: 0.1246, Precision: 0.1246, Recall: 1.0000, AUC: 0.5275, Avg Metric: 0.5507


100%|██████████| 59/59 [02:47<00:00,  2.84s/it]


Confusion Matrix:
[[  0 548]
 [  0  78]]
Epoch 58/100, Train Loss: 51.9151, Train Accuracy: 0.1250
Epoch 58/100, Val Accuracy: 0.1246, Precision: 0.1246, Recall: 1.0000, AUC: 0.5073, Avg Metric: 0.5440


100%|██████████| 59/59 [02:47<00:00,  2.84s/it]


Confusion Matrix:
[[  0 548]
 [  0  78]]
Epoch 59/100, Train Loss: 51.7652, Train Accuracy: 0.1250
Epoch 59/100, Val Accuracy: 0.1246, Precision: 0.1246, Recall: 1.0000, AUC: 0.5164, Avg Metric: 0.5470


100%|██████████| 59/59 [02:47<00:00,  2.83s/it]


Confusion Matrix:
[[  0 548]
 [  0  78]]
Epoch 60/100, Train Loss: 51.0780, Train Accuracy: 0.1250
Epoch 60/100, Val Accuracy: 0.1246, Precision: 0.1246, Recall: 1.0000, AUC: 0.5040, Avg Metric: 0.5429


100%|██████████| 59/59 [02:47<00:00,  2.84s/it]


Confusion Matrix:
[[  0 548]
 [  0  78]]
Epoch 61/100, Train Loss: 50.5865, Train Accuracy: 0.1250
Epoch 61/100, Val Accuracy: 0.1246, Precision: 0.1246, Recall: 1.0000, AUC: 0.4976, Avg Metric: 0.5407


100%|██████████| 59/59 [02:48<00:00,  2.85s/it]


Confusion Matrix:
[[  0 548]
 [  0  78]]
Epoch 62/100, Train Loss: 51.7090, Train Accuracy: 0.1250
Epoch 62/100, Val Accuracy: 0.1246, Precision: 0.1246, Recall: 1.0000, AUC: 0.5213, Avg Metric: 0.5486


100%|██████████| 59/59 [02:47<00:00,  2.84s/it]


Confusion Matrix:
[[  0 548]
 [  0  78]]
Epoch 63/100, Train Loss: 51.3345, Train Accuracy: 0.1250
Epoch 63/100, Val Accuracy: 0.1246, Precision: 0.1246, Recall: 1.0000, AUC: 0.5078, Avg Metric: 0.5441


100%|██████████| 59/59 [02:47<00:00,  2.84s/it]


Confusion Matrix:
[[  0 548]
 [  0  78]]
Epoch 64/100, Train Loss: 50.2817, Train Accuracy: 0.1250
Epoch 64/100, Val Accuracy: 0.1246, Precision: 0.1246, Recall: 1.0000, AUC: 0.5274, Avg Metric: 0.5507


100%|██████████| 59/59 [02:47<00:00,  2.85s/it]


Confusion Matrix:
[[  0 548]
 [  0  78]]
Epoch 65/100, Train Loss: 50.6984, Train Accuracy: 0.1250
Epoch 65/100, Val Accuracy: 0.1246, Precision: 0.1246, Recall: 1.0000, AUC: 0.4937, Avg Metric: 0.5394


100%|██████████| 59/59 [02:48<00:00,  2.85s/it]


Confusion Matrix:
[[  0 548]
 [  0  78]]
Epoch 66/100, Train Loss: 51.0875, Train Accuracy: 0.1250
Epoch 66/100, Val Accuracy: 0.1246, Precision: 0.1246, Recall: 1.0000, AUC: 0.5555, Avg Metric: 0.5600


100%|██████████| 59/59 [02:47<00:00,  2.85s/it]


Confusion Matrix:
[[  0 548]
 [  0  78]]
Epoch 67/100, Train Loss: 50.3486, Train Accuracy: 0.1250
Epoch 67/100, Val Accuracy: 0.1246, Precision: 0.1246, Recall: 1.0000, AUC: 0.5109, Avg Metric: 0.5452


100%|██████████| 59/59 [02:47<00:00,  2.84s/it]


Confusion Matrix:
[[  0 548]
 [  0  78]]
Epoch 68/100, Train Loss: 50.6909, Train Accuracy: 0.1250
Epoch 68/100, Val Accuracy: 0.1246, Precision: 0.1246, Recall: 1.0000, AUC: 0.5470, Avg Metric: 0.5572


100%|██████████| 59/59 [02:47<00:00,  2.85s/it]


Confusion Matrix:
[[  0 548]
 [  0  78]]
Epoch 69/100, Train Loss: 50.0499, Train Accuracy: 0.1250
Epoch 69/100, Val Accuracy: 0.1246, Precision: 0.1246, Recall: 1.0000, AUC: 0.5333, Avg Metric: 0.5526


100%|██████████| 59/59 [02:48<00:00,  2.85s/it]


Confusion Matrix:
[[  0 548]
 [  0  78]]
Epoch 70/100, Train Loss: 49.1321, Train Accuracy: 0.1250
Epoch 70/100, Val Accuracy: 0.1246, Precision: 0.1246, Recall: 1.0000, AUC: 0.5600, Avg Metric: 0.5615


100%|██████████| 59/59 [02:48<00:00,  2.85s/it]


Confusion Matrix:
[[  0 548]
 [  0  78]]
Epoch 71/100, Train Loss: 49.2206, Train Accuracy: 0.1250
Epoch 71/100, Val Accuracy: 0.1246, Precision: 0.1246, Recall: 1.0000, AUC: 0.5197, Avg Metric: 0.5481


100%|██████████| 59/59 [02:48<00:00,  2.85s/it]


Confusion Matrix:
[[  0 548]
 [  0  78]]
Epoch 72/100, Train Loss: 49.9079, Train Accuracy: 0.1250
Epoch 72/100, Val Accuracy: 0.1246, Precision: 0.1246, Recall: 1.0000, AUC: 0.5180, Avg Metric: 0.5475


100%|██████████| 59/59 [02:48<00:00,  2.85s/it]


Confusion Matrix:
[[  0 548]
 [  0  78]]
Epoch 73/100, Train Loss: 49.3599, Train Accuracy: 0.1250
Epoch 73/100, Val Accuracy: 0.1246, Precision: 0.1246, Recall: 1.0000, AUC: 0.5621, Avg Metric: 0.5622


100%|██████████| 59/59 [02:48<00:00,  2.85s/it]


Confusion Matrix:
[[  0 548]
 [  0  78]]
Epoch 74/100, Train Loss: 48.8096, Train Accuracy: 0.1250
Epoch 74/100, Val Accuracy: 0.1246, Precision: 0.1246, Recall: 1.0000, AUC: 0.5307, Avg Metric: 0.5518


100%|██████████| 59/59 [02:48<00:00,  2.85s/it]


Confusion Matrix:
[[  0 548]
 [  0  78]]
Epoch 75/100, Train Loss: 48.8552, Train Accuracy: 0.1250
Epoch 75/100, Val Accuracy: 0.1246, Precision: 0.1246, Recall: 1.0000, AUC: 0.5622, Avg Metric: 0.5623


100%|██████████| 59/59 [02:48<00:00,  2.85s/it]


Confusion Matrix:
[[  0 548]
 [  0  78]]
Epoch 76/100, Train Loss: 49.0523, Train Accuracy: 0.1250
Epoch 76/100, Val Accuracy: 0.1246, Precision: 0.1246, Recall: 1.0000, AUC: 0.5389, Avg Metric: 0.5545


100%|██████████| 59/59 [02:47<00:00,  2.85s/it]


Confusion Matrix:
[[  0 548]
 [  0  78]]
Epoch 77/100, Train Loss: 47.6694, Train Accuracy: 0.1250
Epoch 77/100, Val Accuracy: 0.1246, Precision: 0.1246, Recall: 1.0000, AUC: 0.5174, Avg Metric: 0.5473


100%|██████████| 59/59 [02:47<00:00,  2.85s/it]


Confusion Matrix:
[[  0 548]
 [  0  78]]
Epoch 78/100, Train Loss: 46.8906, Train Accuracy: 0.1250
Epoch 78/100, Val Accuracy: 0.1246, Precision: 0.1246, Recall: 1.0000, AUC: 0.5325, Avg Metric: 0.5524


100%|██████████| 59/59 [02:48<00:00,  2.85s/it]


Confusion Matrix:
[[  0 548]
 [  0  78]]
Epoch 79/100, Train Loss: 48.0183, Train Accuracy: 0.1250
Epoch 79/100, Val Accuracy: 0.1246, Precision: 0.1246, Recall: 1.0000, AUC: 0.5215, Avg Metric: 0.5487


100%|██████████| 59/59 [02:48<00:00,  2.85s/it]


Confusion Matrix:
[[  0 548]
 [  0  78]]
Epoch 80/100, Train Loss: 47.4470, Train Accuracy: 0.1250
Epoch 80/100, Val Accuracy: 0.1246, Precision: 0.1246, Recall: 1.0000, AUC: 0.5537, Avg Metric: 0.5594


100%|██████████| 59/59 [02:48<00:00,  2.85s/it]


Confusion Matrix:
[[  0 548]
 [  0  78]]
Epoch 81/100, Train Loss: 48.9543, Train Accuracy: 0.1250
Epoch 81/100, Val Accuracy: 0.1246, Precision: 0.1246, Recall: 1.0000, AUC: 0.5157, Avg Metric: 0.5468


100%|██████████| 59/59 [02:47<00:00,  2.85s/it]


Confusion Matrix:
[[  0 548]
 [  0  78]]
Epoch 82/100, Train Loss: 45.9247, Train Accuracy: 0.1250
Epoch 82/100, Val Accuracy: 0.1246, Precision: 0.1246, Recall: 1.0000, AUC: 0.4999, Avg Metric: 0.5415


100%|██████████| 59/59 [02:48<00:00,  2.85s/it]


Confusion Matrix:
[[  0 548]
 [  0  78]]
Epoch 83/100, Train Loss: 45.8322, Train Accuracy: 0.1250
Epoch 83/100, Val Accuracy: 0.1246, Precision: 0.1246, Recall: 1.0000, AUC: 0.5453, Avg Metric: 0.5566


100%|██████████| 59/59 [02:48<00:00,  2.85s/it]


Confusion Matrix:
[[  0 548]
 [  0  78]]
Epoch 84/100, Train Loss: 47.0941, Train Accuracy: 0.1250
Epoch 84/100, Val Accuracy: 0.1246, Precision: 0.1246, Recall: 1.0000, AUC: 0.5224, Avg Metric: 0.5490


100%|██████████| 59/59 [02:48<00:00,  2.85s/it]


Confusion Matrix:
[[  0 548]
 [  0  78]]
Epoch 85/100, Train Loss: 44.7778, Train Accuracy: 0.1250
Epoch 85/100, Val Accuracy: 0.1246, Precision: 0.1246, Recall: 1.0000, AUC: 0.5303, Avg Metric: 0.5516


100%|██████████| 59/59 [02:48<00:00,  2.85s/it]


Confusion Matrix:
[[  0 548]
 [  0  78]]
Epoch 86/100, Train Loss: 46.2117, Train Accuracy: 0.1250
Epoch 86/100, Val Accuracy: 0.1246, Precision: 0.1246, Recall: 1.0000, AUC: 0.5430, Avg Metric: 0.5559


100%|██████████| 59/59 [02:48<00:00,  2.85s/it]


Confusion Matrix:
[[  0 548]
 [  0  78]]
Epoch 87/100, Train Loss: 43.9924, Train Accuracy: 0.1250
Epoch 87/100, Val Accuracy: 0.1246, Precision: 0.1246, Recall: 1.0000, AUC: 0.5229, Avg Metric: 0.5492


100%|██████████| 59/59 [02:47<00:00,  2.84s/it]


Confusion Matrix:
[[  0 548]
 [  0  78]]
Epoch 88/100, Train Loss: 46.3648, Train Accuracy: 0.1250
Epoch 88/100, Val Accuracy: 0.1246, Precision: 0.1246, Recall: 1.0000, AUC: 0.5186, Avg Metric: 0.5477


100%|██████████| 59/59 [02:47<00:00,  2.84s/it]


Confusion Matrix:
[[  0 548]
 [  0  78]]
Epoch 89/100, Train Loss: 43.7827, Train Accuracy: 0.1250
Epoch 89/100, Val Accuracy: 0.1246, Precision: 0.1246, Recall: 1.0000, AUC: 0.5266, Avg Metric: 0.5504


100%|██████████| 59/59 [02:47<00:00,  2.85s/it]


Confusion Matrix:
[[  0 548]
 [  0  78]]
Epoch 90/100, Train Loss: 42.7669, Train Accuracy: 0.1250
Epoch 90/100, Val Accuracy: 0.1246, Precision: 0.1246, Recall: 1.0000, AUC: 0.5247, Avg Metric: 0.5498


100%|██████████| 59/59 [02:48<00:00,  2.85s/it]


Confusion Matrix:
[[  0 548]
 [  0  78]]
Epoch 91/100, Train Loss: 44.0819, Train Accuracy: 0.1250
Epoch 91/100, Val Accuracy: 0.1246, Precision: 0.1246, Recall: 1.0000, AUC: 0.5166, Avg Metric: 0.5471


100%|██████████| 59/59 [02:48<00:00,  2.85s/it]


Confusion Matrix:
[[  0 548]
 [  0  78]]
Epoch 92/100, Train Loss: 43.5474, Train Accuracy: 0.1250
Epoch 92/100, Val Accuracy: 0.1246, Precision: 0.1246, Recall: 1.0000, AUC: 0.5579, Avg Metric: 0.5609


100%|██████████| 59/59 [02:48<00:00,  2.85s/it]


Confusion Matrix:
[[  0 548]
 [  0  78]]
Epoch 93/100, Train Loss: 41.8880, Train Accuracy: 0.1250
Epoch 93/100, Val Accuracy: 0.1246, Precision: 0.1246, Recall: 1.0000, AUC: 0.5259, Avg Metric: 0.5502


 46%|████▌     | 27/59 [01:20<01:34,  2.97s/it]


KeyboardInterrupt: 

In [12]:
model = MriResentModel(20,1).to(device)
model.load_state_dict(torch.load(f"saved_models/{model_name}.pth"))

/Users/fateme/Projects/iaaa-project/iaaa-venv/lib/python3.12/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/Users/fateme/Projects/iaaa-project/iaaa-venv/lib/python3.12/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=ResNet50_Weights.IMAGENET1K_V1`. You can also use `weights=ResNet50_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)


<All keys matched successfully>

In [13]:
tester = Tester(
    model=model,
    test_dl=test_dl,
    test_dataset=test_dataset,
    device=device,
    threshold=0  # Set the threshold for binary classification
)

# Perform testing and print metrics
tester.test()

Test Accuracy: 0.7604, Precision: 0.2049, Recall: 0.3205, AUC: 0.5926, Avg Metric: 0.3727
